### ISSUE TITLE
new cbor_encode_text_string() incompatible with C99

### ISSUE THREAD

**Issue by CaryChu** [mononn/cbor#10]
The new cbor_encode_text_string() function uses strnlen() which is a C11 function. Also, the new function no longer takes text length as a parameter. I find the old function more useful. I suggest that the library has one function takes in length as parameter and one does not. The one using strnlen() can be compiled out when C99 compiler is used.

**Comment by onkwon** [comment]
Please check out #11 if it looks good to you and there is anything else to improve.

I reverted the function as you'd like. And add `cbor_encode_null_terminated_text_string()` for use without string length.

Thank you very much for your suggestion.
